#!/bin/bash
set -e
eval "$("$(dirname "$0")"/adr-config)"

source "$(dirname $0)/_adr_database"

## usage: adr generate database
##
## Generates a database with all fields from the ADR

createDatabase
populateDatabase