#!/bin/bash
set -e
eval "$("$(dirname "$0")"/adr-config)"

## usage: adr generate database
##
## Generates a database with all fields from the ADR

function createDatabase() {
  cat <<EOF | sqlite3 _adr.db
DROP TABLE IF EXISTS adr;
CREATE TABLE adr(
  id int,
  title varchar,
  link varchar,
  proposed datetime,
  decision datetime,
  status varchar,
  priority varchar
);
EOF
}

function insertIntoDatabase() {
  cat <<EOF | sqlite3 _adr.db
INSERT INTO adr VALUES(${1}, '${2}', '${3}', '${4}', '${5}', '${6}', '${7}');
EOF
}

function populateDatabase() {
  for file in $("$adr_bin_dir/adr-list")
  do
      local id=$("$adr_bin_dir/_adr_id" $file)
      local title=$("$adr_bin_dir/_adr_title" $file)
      local link=${link_prefix}$(basename $file)

      local proposed=$("$adr_bin_dir/_adr_field" "Proposed Date" "$link")
      local decision=$("$adr_bin_dir/_adr_field" "Decision Date" "$link")
      local status=$("$adr_bin_dir/_adr_field" "Status" "$link")
      local priority=$("$adr_bin_dir/_adr_field" "Priority" "$link")

      insertIntoDatabase "$id" "$title" "$link" "$proposed" "$decision" "$status" "$priority"
  done
}

function selectFromDatabase() {
  cat <<EOF | sqlite3 _adr.db
$*
EOF
}