#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

source "$(dirname $0)/_record_database"

## usage: record generate database
##
## Generates a database with all fields from the ADR

createDatabase
populateDatabase
