#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

source=$("$record_bin_dir/_record_file" "${record_type}" "${1:?Source is unset or null}")
link_type="${2:?Link type is unset or null}"
target=$("$record_bin_dir/_record_file" "${record_type}" "${3:?Target is unset or null}")
target_title="$("$record_bin_dir/_record_title" "${record_type}" "$target")"

awk -v link_type="$link_type" -v target="$(basename $target)" -v target_title="$target_title" '
    BEGIN {
        in_info_section=0
    }
    /^##/ {
        if (in_info_section) {
            print link_type " [" target_title "](" target ")"
            print ""
        }
        in_info_section=0
    }
    /^==/ {
        if (in_info_section) {
            print link_type " link:" target "[" target_title "]"
            print ""
        }
        in_info_section=0
    }
    /^[=#]{2} Further Information$/ {
        in_info_section=1
    }
    { print }
' "${source}" >"${source}.tmp"

mv "${source}.tmp" "${source}"
