#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

file_type=$("$record_bin_dir/_record_get_conf" "${record_type}" ".record-file-type")

if [ "$file_type" = "adoc" ]; then
    "$record_bin_dir/_record_field" "${record_type}" Status "${1}" | sed -n -E 's/^(.+) link:0*([1-9][0-9]*).*\[.*\]/\2=\1/p'
else
    "$record_bin_dir/_record_field" "${record_type}" Status "${1}" | sed -n -E 's/^(.+) \[.*\]\(0*([1-9][0-9]*).*\)/\2=\1/p'
fi
