#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

dbname=_records.db

## usage: record generate database RECORD_TYPE
##
## Generates a database with all fields from the record

function createDatabase() {
    cat <<EOF | sqlite3 "$dbname"
DROP TABLE IF EXISTS records;
CREATE TABLE records(
  id int,
  record_type varchar,
  title varchar,
  link varchar,
  proposed datetime,
  decision datetime,
  status varchar,
  prio_or_sever varchar
);
EOF
}

function insertIntoDatabase() {
  cat <<EOF | sqlite3 "$dbname"
INSERT INTO records VALUES(${1}, '${2}', '${3}', '${4}', '${5}', '${6}', '${7}', '${8}');
EOF
}

function populateDatabase() {
    for rec_type in adr tdr; do
        for file in $("$record_bin_dir/record-list" "${rec_type}"); do
            local id=$("$record_bin_dir/_record_id" "${rec_type}" "${file}")
            local title=$("$record_bin_dir/_record_title" "${rec_type}" "${file}")
            local link=${link_prefix}$(basename "${file}")

            local proposed=$("$record_bin_dir/_record_field" "${rec_type}" "Proposed Date" "${link}")
            local decision=$("$record_bin_dir/_record_field" "${rec_type}" "Decision Date" "${link}")
            local status=$("$record_bin_dir/_record_field" "${rec_type}" "Status" "${link}")

            local prio_or_sever=$("$record_bin_dir/_record_field" "${rec_type}" "Priority" "${link}")

            if [ -z "${prio_or_sever}" ]; then
                prio_or_sever=$("$record_bin_dir/_record_field" "${rec_type}" "Severity" "${link}")
            fi

            insertIntoDatabase "$id" "${rec_type}" "${title}" "${link}" "${proposed}" "${decision}" "${status}" "${prio_or_sever}"
        done
    done
}

function selectFromDatabase() {
    cat <<EOF | sqlite3 "$dbname"
$*
EOF
}
