#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

grep -E '^[=#] [0-9]+.*$' "$("$record_bin_dir/_record_file" "${record_type}" "${1}")" | cut -c 3- | cut -d . -f 1
