#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

for f in $(cd "$record_bin_dir" && find . -name 'record-*'); do
    if [ -x "$record_bin_dir/$f" ]; then
        echo "$f" | cut -c 7-
    fi
done
