#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

cmds=("$@")

if ((${#@} == 1)); then
    cmdexe="$record_bin_dir/adr-$1"
elif ((${#@} > 1)); then
    cmdexe="$record_bin_dir/_record_$(
        IFS=_
        echo "${cmds[*]}"
    )"
fi

helpexe="$record_bin_dir/_record_help_$(
    IFS=_
    echo "${cmds[*]}"
)"

if [ -z "$cmds" -o \( ! -x "$cmdexe" -a ! -x "$helpexe" \) ]; then
    echo "usage: record help COMMAND [ARG] ..."
    echo "COMMAND is one of: "
    $record_bin_dir/_record_commands | sed 's/^/  /'
    echo "Run 'record help COMMAND' for help on a specific command."
else
    if [ -x "$helpexe" ]; then
        "$helpexe"
    else
        grep -E '^##' "$cmdexe" | cut -c 4-
    fi

    # Assumes only two levels of command / subcommand.
    subcmds=($(compgen -G "$record_bin_dir/_record_$1_"'*'))

    if ((${#subcmds} > 0)); then
        echo
        echo Subcommands:
        for f in "${subcmds[@]}"; do
            basename $f | cut -c $((${#1} + 7))-
        done | sed "s/^/  adr $1 /"
    fi
fi
