#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

source "$(dirname $0)/_record_database"

## usage: record generate rss RECORD_TYPE
##
## Generates a rss feed with contents

#################
# Actual output #
#################

cat <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

<!--
//////////////////////////////////////////////////////////////
/                                                            /
/ Do not change this file - all changes will be overwritten! /
/                                                            /
//////////////////////////////////////////////////////////////
-->

  <channel>
    <title>List of all ${record_type} records</title>
    <description>List of all created ${record_type} records</description>
    <ttl>240</ttl>
    <lastBuildDate>$(date -u +'%Y-%m-%d %H:%M')</lastBuildDate>
    <generator>record-tools</generator>
    <webmaster>christoph@unexist.dev</webmaster>
EOF

echo $(selectFromDatabase $(
    cat <<EOF
SELECT
  '<item><title>' || title || '</title>',
  '<link>' || link || '</link>',
  '<category>' || prio_or_sever || '</category>',
  '<pubDate>' || proposed || '</pubDate>',
  '<description>Status: ' || status || '</description></item>'
FROM records
WHERE record_type = '${record_type}'
EOF
)) | tr -d "|"

cat <<EOF
  </channel>
</rss>
EOF
