#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

title="$1"
link="$2"
file_type="$($record_bin_dir/_record_file_type)"

if [ "$file_type" = "md" ]; then
    printf "[%s](%s)" "$title" "$link"
else
    printf "link:%s[%s]" "$link" "$title"
fi
