#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

level=$1
text="$2"
file_type="$($record_bin_dir/_record_file_type)"

if [ "$file_type" = "md" ]; then
    printf '#%.0s' {1..$level}
else
    printf '=%.0s' {1..$level}
fi
printf ' %s' "$text"
