#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

level=$1
text="$2"
file_type=$("$record_bin_dir/_record_file_type" "${record_type}")

if [ "$file_type" = "adoc" ]; then
    printf '=%.0s' {1..$level}
else
    printf '#%.0s' {1..$level}
fi
printf ' %s' "$text"
