#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

grep "^| $1" "$("$record_bin_dir/_record_file" "${record_type}" "${2}")" | cut -d '|' -f 3 | tr -d ' |'
