#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

reldir=.

function mkrel() {
    local d=$reldir/$1
    echo ${d#./}
}

function absdir() {
    (cd $(dirname $1) && pwd -P)
}

# Default path
record_default_dir="architecture-decision-records"
if [ "tdr" = "$record_type" ]; then
    record_default_dir="technical-debts-records"
fi

while [ "$(absdir "$reldir")" != / ]; do
    if [ -f $(mkrel .record-${record_type}-dir) ]; then
        mkrel $(cat $(mkrel .record-${record_type}-dir))
        exit
    elif [ -d $(mkrel doc/${record_default_dir}) ]; then
        mkrel doc/${record_default_dir}
        exit
    else
        reldir=$reldir/..
    fi
done
echo doc/${record_default_dir}
