#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

title="$1"
link="$2"
file_type=$("$record_bin_dir/_record_get_conf" "${record_type}" ".record-file-type")

if [ "$file_type" = "adoc" ]; then
    printf "link:%s[%s]" "${link}" "${title}"
else
    printf "[%s](%s)" "${title}" "${link}"
fi
