#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

awk '
/^[#=]{2} Status/,/^[#=]/ && !/^[#=]{2} Status/ {
	if (!/^([#=]|\s*$)/) print
}
' "$("$record_bin_dir/_record_file" "${record_type}" "$1")"
