#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

source=$("$record_bin_dir/_record_file" "${record_type}" "${1:?SOURCE}")
link_type="${2:?LINK TYPE}"
target=$("$record_bin_dir/_record_file" "${record_type}" "${3:?TARGET}")

target_title="$("$record_bin_dir/_record_title" "${record_type}" "$target")"

awk -v link_type="$link_type" -v target="$(basename $target)" -v target_title="$target_title" '
	BEGIN {
		in_status_section=0
	}
	/^##/ {
		if (in_status_section) {
		    print link_type " [" target_title "](" target ")"
			print ""
		}
		in_status_section=0
	}
	/^==/ {
		if (in_status_section) {
      print link_type " link:" target "[" target_title "]"
			print ""
		}
		in_status_section=0
	}
	/^[#=]{2} Status$/ {
		in_status_section=1
	}
	{ print }
' "$source" >"$source.tmp"

mv "$source.tmp" "$source"
