#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

for cmd in $(find "${record_bin_dir}" -name 'record-*'); do
    if [ -x "$cmd" ]; then
        echo "$cmd" | awk -F '/' '{print $NF}'
    fi
done
