#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

level=${1:?Level is unset or null}
text="${2:?Text is unset or null}"
file_type=$("$record_bin_dir/_record_get_conf" "${record_type}" ".record-file-type")

if [ "$file_type" = "adoc" ]; then
    printf '=%.0s' {1..$level}
else
    printf '#%.0s' {1..$level}
fi
printf ' %s' "$text"
