#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

source "$(dirname $0)/_record_database"

## usage: record generate rss RECORD_TYPE
##
## Generates a rss feed with contents

#################
# Actual output #
#################

cat <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<feed version="2.0">

<!--
//////////////////////////////////////////////////////////////
/                                                            /
/ Do not change this file - all changes will be overwritten! /
/                                                            /
//////////////////////////////////////////////////////////////
-->

  <title>List of all ${record_type} records</title>
  <description>List of all created ${record_type} records</description>
  <updated>$(date -u +'%Y-%m-%d %H:%M')</updated>
  <generator>record-tools</generator>
  <author>
    <name>christoph@unexist.dev</name>
  </author>
EOF

echo $(selectFromDatabase $(
    cat <<EOF
SELECT
  '<entry><title>' || title || '</title>',
  '<link>' || link || '</link>',
  '<id>' || id || '</id>',
  '<updated>' || proposed || '</updated>',
  '<summary>' || prio_or_sever || '</summary>',
  '<content>Status: ' || status || '</content></entry>'
FROM records
WHERE record_type = '${record_type}'
EOF
)) | tr -d "|"

cat <<EOF
</feed>
EOF
