#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

file_type="$($record_bin_dir/_record_file_type)"

if [ "$file_type" = "md" ]; then
    "$record_bin_dir/_record_status" "${record_type}" "$1" | sed -n -E 's/^(.+) \[.*\]\(0*([1-9][0-9]*).*\)/\2=\1/p'
else
    "$record_bin_dir/_record_status" "${record_type}" "$1" | sed -n -E 's/^(.+) link:0*([1-9][0-9]*).*\[.*\]/\2=\1/p'
fi
