#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

## usage: record link RECORD_TYPE SOURCE LINK TARGET REVERSE-LINK
##
## Creates a link between two records, from SOURCE to TARGET new.
## SOURCE and TARGET are both a reference (number or partial filename) to an record
## LINK is the description of the link created in the SOURCE.
## REVERSE-LINK is the description of the link created in the TARGET
##
## E.g. to create link record 12 to record 10
##
##     record-adr link 12 Amends 10 "Amended by"
##

source="${1:?SOURCE}"
forward_link="${2:?LINK}"
target="${3:?TARGET}"
reverse_link="${4:?REVERSE-LINK}"

"$record_bin_dir/_record_add_link" "${record_type}" "$source" "$forward_link" "$target"
"$record_bin_dir/_record_add_link" "${record_type}" "$target" "$reverse_link" "$source"
