#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo ${1:-adr} | tr '[:upper:]' '[:lower:]')
shift

## usage: record link RECORD_TYPE SOURCE LINK TARGET REVERSE-LINK
##
## Creates a link between two records, from SOURCE to TARGET new.
## SOURCE and TARGET are both a reference (number or partial filename) to an record
## LINK is the description of the link created in the SOURCE.
## REVERSE-LINK is the description of the link created in the TARGET
##
## E.g. to create link ADR 12 to ADR 10
##
##     record-adr link 12 Amends 10 "Amended by"
##

source="${1}"
forward_link="${2}"
target="${3}"
reverse_link="${4}"

if ! [ -z "${source}" ] && ! [ -z "${forward_link}" ] && ! [ -z "${target}" ] && ! [ -z "${reverse_link}" ]; then
    "$record_bin_dir/_record_add_link" "${record_type}" "${source}" "${forward_link}" "${target}"
    "$record_bin_dir/_record_add_link" "${record_type}" "${target}" "${reverse_link}" "${source}"
else
    "$record_bin_dir"/record-help "${record_type}" link
    exit 1
fi
