#!/bin/bash
set -e
eval "$($(dirname $0)/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

## usage: record help RECORD_TYPE [COMMAND [SUBCOMMAND...]]
##
## If COMMAND and any SUBCOMMANDs are given, displays help for that command.
## Otherwise lists the available commands.
##
## Uses the environment variables ADR_PAGER or PAGER (in that order) to
## specify the command to be used to display the help text.  The default
## pager is: more.

pager="${RECORD_PAGER:-${PAGER:-more}}"

("$record_bin_dir/_record_help" "${record_type}" "$@") | $pager
