#!/bin/bash
set -e
eval "$("$(dirname "$0")"/record-config)"

# Handle record type
record_type=$(echo $1 | tr '[:upper:]' '[:lower:]')
shift

## usage: record generate RECORD_TYPE [REPORT [OPTION ...]]
##
## Generates summary documentation about the architecture decision records
## that is typically fed into the tool chain for publishing a project's
## documentation.
##
## To list the report types that can be generated, run:
##
##     record generate
##
## To get help on a specific report generator, run:
##
##     record help generate <report-type>
##
## For example, the following command will run the "toc" (table of contents)
## generator:
##
##     record generate toc
##
## The following command will display help for the "toc" generator:
##
##     record help generate toc

cmd=$1
echo $record_bin_dir >log.1
echo $cmd >>log.1

if [ -z $cmd ]; then
    (cd "$record_bin_dir" && find . -name '_record_generate_*') | cut -c 17-
else
    "$record_bin_dir/_record_generate_$cmd" "${record_type}" "${@:2}"
fi
